.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "NODE\-UPDATE" "8" "December 2014" "" ""
.
.SH "NAME"
\fBnode\-update\fR \- update a portable Node\.js installation
.
.SH "SYNOPSIS"
\fBnode\-update\fR
.
.SH "DESCRIPTION"
This command downloads the latest Node\.js version for the specified architecture in the specified directory, without overriding the whole installation\.
.
.SH "OPTIONS"
.
.TP
\fB\-a\fR, \fB\-\-arch\fR=\fIarch\fR
The architecture to use (\fBx64\fR by default)\.
.
.TP
\fB\-t\fR, \fB\-\-target\-dir\fR=\fItarget\fR
The target directory for the Node\.js installation (default is current directory)\.
.
.SH "SEE ALSO"
\fIhttp://www\.nodejs\.org/\fR, \fBcurl\fR(1), \fBtar\fR(1)
